substitutions:
  _REGION: "us-east1"
  _SERVICE: "ttriplej"
  _REPO: "my-repo"          # artifact registry repo (or skip for gcr)
options:
  logging: CLOUD_LOGGING_ONLY
steps:
# Build the image and push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - '-t'
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
  - '.'
# Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA']
# Deploy to Cloud Run (uses Secret Manager secret MONGODB_URI)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE}'
  - '--image'
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-secrets'
  - 'MONGODB_URI=projects/1078260948749/secrets/MONGODB_URI'
images:
 - 'us-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'